# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: mariadb-galera
      image: docker.io/helmhubio/mariadb-galera:12.0.2-debian-12-r0
    - name: mysqld-exporter
      image: docker.io/helmhubio/mysqld-exporter:0.17.2-debian-12-r16
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 12.0.2
dependencies:
- name: common
  repository: oci://registry-1.docker.io/helmhubiocharts
  tags:
  - bitnami-common
  version: 2.x.x
description: MariaDB Galera is a multi-primary database cluster solution for synchronous replication and high availability.
home: https://github.com/helmhub-io/charts
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/mariadb-galera/img/mariadb-galera-stack-220x234.png
keywords:
- mariadb
- mysql
- database
- sql
- prometheus
- galera
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/helmhub-io/charts
name: mariadb-galera
sources:
- https://github.com/helmhub-io/charts/tree/main/helmhubio/mariadb-galera
version: 16.0.2
