# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: metallb-controller
      image: docker.io/helmhubio/metallb-controller:0.15.2-debian-12-r7
    - name: metallb-speaker
      image: docker.io/helmhubio/metallb-speaker:0.15.2-debian-12-r6
  licenses: Apache-2.0
  tanzuCategory: clusterUtility
apiVersion: v2
appVersion: 0.15.2
dependencies:
- name: common
  repository: oci://registry-1.docker.io/helmhubiocharts
  tags:
  - bitnami-common
  version: 2.x.x
description: MetalLB is a load-balancer implementation for bare metal Kubernetes clusters, using standard routing protocols.
home: https://github.com/helmhub-io/charts
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/metallb-speaker/img/metallb-speaker-stack-220x234.png
keywords:
- load-balancer
- balancer
- lb
- bgp
- arp
- vrrp
- vip
kubeVersion: '>= 1.19.0-0'
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/helmhub-io/charts
name: metallb
sources:
- https://github.com/helmhub-io/charts/tree/main/helmhubio/metallb
version: 6.4.23
