# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: gitea
      image: docker.io/helmhubio/gitea:1.24.5
    - name: os-shell
      image: docker.io/helmhubio/os-shell:12-debian-12-r51
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 1.24.5
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/helmhubiocharts
  version: 16.x.x
- name: common
  repository: oci://registry-1.docker.io/helmhubiocharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Gitea is a lightweight code hosting solution. Written in Go, features low resource consumption, easy upgrades and multiple databases.
home: https://github.com/helmhub-io/charts
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/gitea/img/gitea-stack-220x234.png
keywords:
- gitea
- analytics
- http
- web
- application
- php
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/helmhub-io/charts
name: gitea
sources:
- https://github.com/helmhub-io/charts/tree/main/helmhubio/gitea
version: 3.2.23
