# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: mastodon
      image: docker.io/helmhubio/mastodon:4.4.3-debian-12-r11
    - name: os-shell
      image: docker.io/helmhubio/os-shell:12-debian-12-r51
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 4.4.3
dependencies:
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/helmhubiocharts
  version: 22.x.x
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/helmhubiocharts
  version: 16.x.x
- condition: elasticsearch.enabled
  name: elasticsearch
  repository: oci://registry-1.docker.io/helmhubiocharts
  version: 22.x.x
- condition: minio.enabled
  name: minio
  repository: oci://registry-1.docker.io/helmhubiocharts
  version: 17.x.x
- condition: apache.enabled
  name: apache
  repository: oci://registry-1.docker.io/helmhubiocharts
  version: 11.x.x
- name: common
  repository: oci://registry-1.docker.io/helmhubiocharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Mastodon is self-hosted social network server based on ActivityPub. Written in Ruby, features real-time updates, multimedia attachments and no vendor lock-in.
home: https://github.com/helmhub-io/charts
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/mastodon/img/mastodon-stack-220x234.png
keywords:
- development
- dashboards
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/helmhub-io/charts
name: mastodon
sources:
- https://github.com/helmhub-io/charts/tree/main/helmhubio/mastodon
version: 14.0.1
