# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: ejbca
      image: docker.io/helmhubio/ejbca:9.1.1-debian-12-r12
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 9.1.1
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: oci://registry-1.docker.io/helmhubiocharts
  tags:
  - ejbca-database
  version: 22.x.x
- name: common
  repository: oci://registry-1.docker.io/helmhubiocharts
  tags:
  - bitnami-common
  version: 2.x.x
description: EJBCA is an enterprise class PKI Certificate Authority software, built using Java (JEE) technology.
home: https://github.com/helmhub-io/charts
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/ejbca/img/ejbca-stack-220x234.png
keywords:
- ejbca
- ca
- pki
- certificate
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/helmhub-io/charts
name: ejbca
sources:
- https://github.com/helmhub-io/charts/tree/main/helmhubio/ejbca
version: 19.0.1
