# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: kubectl
      image: docker.io/helmhubio/kubectl:1.33.4-debian-12-r0
    - name: os-shell
      image: docker.io/helmhubio/os-shell:12-debian-12-r51
    - name: redis-exporter
      image: docker.io/helmhubio/redis-exporter:1.76.0-debian-12-r0
    - name: valkey
      image: docker.io/helmhubio/valkey:8.1.3-debian-12-r3
    - name: valkey-sentinel
      image: docker.io/helmhubio/valkey-sentinel:8.1.3-debian-12-r3
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 8.1.3
dependencies:
- name: common
  repository: oci://registry-1.docker.io/helmhubiocharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Valkey is an open source (BSD) high-performance key/value datastore that supports a variety workloads such as caching, message queues, and can act as a primary database.
home: https://github.com/helmhub-io/charts
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/valkey/img/valkey-stack-220x234.png
keywords:
- valkey
- keyvalue
- database
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/helmhub-io/charts
name: valkey
sources:
- https://github.com/helmhub-io/charts/tree/main/helmhubio/valkey
version: 4.0.1
