# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: cloudnative-pg
      image: docker.io/helmhubio/cloudnative-pg:1.27.0-debian-12-r1
    - name: plugin-barman-cloud
      image: docker.io/helmhubio/plugin-barman-cloud:0.6.0-debian-12-r0
    - name: plugin-barman-cloud-sidecar
      image: docker.io/helmhubio/plugin-barman-cloud-sidecar:0.6.0-debian-12-r0
    - name: postgresql
      image: docker.io/helmhubio/postgresql:17.6.0-debian-12-r4
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 1.27.0
dependencies:
- name: common
  repository: oci://registry-1.docker.io/helmhubiocharts
  tags:
  - bitnami-common
  version: 2.x.x
description: CloudNativePG is an open-source tool for managing PostgreSQL databases on Kubernetes, from setup to ongoing upkeep.
home: https://github.com/helmhub-io/charts
icon: https://helmhub.io/assets/stacks/cloudnative-pg/img/cloudnative-pg-stack-220x234.png
keywords:
- cloudnative-pg
- operator
- postgresql
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/helmhub-io/charts
name: cloudnative-pg
sources:
- https://github.com/helmhub-io/charts/tree/main/helmhubio/cloudnative-pg
version: 1.0.13
