# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: deepspeed
      image: docker.io/helmhubio/deepspeed:0.17.5-debian-12-r0
    - name: git
      image: docker.io/helmhubio/git:2.51.0-debian-12-r0
    - name: os-shell
      image: docker.io/helmhubio/os-shell:12-debian-12-r51
  licenses: Apache-2.0
  tanzuCategory: clusterUtility
apiVersion: v2
appVersion: 0.17.5
dependencies:
- name: common
  repository: oci://registry-1.docker.io/helmhubiocharts
  tags:
  - bitnami-common
  version: 2.x.x
description: DeepSpeed is deep learning software suite for empowering ChatGPT-like model training. Features dense or sparse model inference, high throughput and high compression.
home: https://github.com/helmhub-io/charts
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/deepspeed/img/deepspeed-stack-220x234.png
keywords:
- deepspeed
- pytorch
- python
- machine
- learning
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/helmhub-io/charts
name: deepspeed
sources:
- https://github.com/helmhub-io/charts/tree/main/helmhubio/deepspeed
- https://github.com/helmhub-io/charts/tree/main/helmhubio/pytorch
version: 2.3.51
