# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: mongodb-exporter
      image: docker.io/helmhubio/mongodb-exporter:0.47.0-debian-12-r1
    - name: mongodb-sharded
      image: docker.io/helmhubio/mongodb-sharded:8.0.13
    - name: os-shell
      image: docker.io/helmhubio/os-shell:12-debian-12-r51
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 8.0.13
dependencies:
- name: common
  repository: oci://registry-1.docker.io/helmhubiocharts
  tags:
  - bitnami-common
  version: 2.x.x
description: MongoDB(R) is an open source NoSQL database that uses JSON for data storage. MongoDB(TM) Sharded improves scalability and reliability for large datasets by distributing data across multiple machines.
home: https://github.com/helmhub-io/charts
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/mongodb/img/mongodb-stack-220x234.png
keywords:
- mongodb
- database
- nosql
- cluster
- replicaset
- replication
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/helmhub-io/charts
name: mongodb-sharded
sources:
- https://github.com/helmhub-io/charts/tree/main/helmhubio/mongodb-sharded
version: 9.4.13
